apiVersion: v1
kind: Namespace
metadata:
  name: hydrological-simulations
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-management
  namespace: hydrological-simulations
rules:
  - apiGroups: ["batch"]
    resources:
      - pods
      - jobs
    verbs:
      - create
      - get
      - list
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-management-account
  namespace: hydrological-simulations
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager
  namespace: hydrological-simulations
subjects:
  - kind: ServiceAccount
    name: job-management-account

roleRef:
  kind: Role
  name: job-management
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-job-management-service
  namespace: hydrological-simulations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation-job-management-service
  template:
    metadata:
      labels:
        app: simulation-job-management-service
    spec:
      serviceAccountName: job-management-account
      containers:
      - name: simulation-job-management-service
        image: watermodelling/simulation-job-management-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: NFS_PVC
          value: <nfs-pvc>
        - name: REDIS_URL_WITH_PORT
          value: <url:port>
---
apiVersion: v1
kind: Service
metadata:
  name: job-management-svc
spec:
  selector:
    app: simulation-job-management-service
  ports:
  - name: simulation-management-webapp
    protocol: TCP
    port: 8080
    targetPort: 8080