apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-app-role
rules:
  - apiGroups: ["batch"]
    resources:
      - pods
      - jobs
    verbs:
      - create
      - get
      - list
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-supervisor
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: web-app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-job-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation-job-management-service
  template:
    metadata:
      labels:
        app: simulation-job-management-service
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - name: simulation-job-management-service
        image: watermodelling/simulation-job-management-service:latest
        # TODO: remove
        imagePullPolicy: Never
#        securityContext:
#          privileged: True
        ports:
        - containerPort: 7777