import os

REDIS_URL = os.environ['REDIS_URL_WITH_PORT']
SIMULATION_NAMESPACE = os.environ["SIMULATION_NAMESPACE"]
PVC_NAME = os.environ['NFS_PVC']
MINIO_SECRET_NAME = os.environ["MINIO_SECRET_NAME"]

BACKOFF_LIMIT = 2
JOB_TTL_IN_SEC = 86400  # 24 * 60 * 60 = 86400 (24h)
